// This file is generated by kconfig_compiler from documentsettings.kcfg.
// All changes you do to this file will be lost.

#include "documentsettings.h"

//#include <klocale.h>
#include <QtCore/QSettings>

DocumentSettings::DocumentSettings(  const QString & fileurl )
  : /*KConfigSkeleton( QLatin1String( "kwordquizrc" ) )
  ,*/ mParamfileurl(fileurl)
{
  readConfig();
}

DocumentSettings::~DocumentSettings()
{

}

void DocumentSettings::readConfig()
{
  QSettings settings;

  settings.beginGroup(QString("Document %1").arg(mParamfileurl));
  mSizeHintColumn[0] = settings.value("SizeHintColumn1", 250).toInt();
  mSizeHintColumn[1] = settings.value("SizeHintColumn2", 250).toInt();
  mKeyboardLayoutColumn[0] = settings.value("KeyboardLayoutColumn1", "").toString();
  mKeyboardLayoutColumn[1] = settings.value("KeyboardLayoutColumn2", "").toString();
  settings.endGroup();
}

void DocumentSettings::writeConfig()
{
  QSettings settings;

  settings.beginGroup(QString("Document %1").arg(mParamfileurl));
  settings.setValue("SizeHintColumn1", mSizeHintColumn[0]);
  settings.setValue("SizeHintColumn2", mSizeHintColumn[1]);
  settings.setValue("KeyboardLayoutColumn1", mKeyboardLayoutColumn[0]);
  settings.setValue("KeyboardLayoutColumn2", mKeyboardLayoutColumn[1]);
  settings.endGroup();
  settings.sync();
}
